Repository chgasparoto/aws-polly-voices, pull requests merged in 2019-10, with the labels that each got.

#8 Added Comma
  README.md
Labels: invalid

#14 Fix package dependencies vulnerabilities
  package-lock.json
Labels: Hacktoberfest

#18 feat: add German helper method
  src/index.js
  test/index.test.js
Labels: Hacktoberfest

#17 add .nvmrc and fix node version to 10.16.3
  .nvmrc
Labels: Hacktoberfest

#10 feat: implement russian helper method
  src/index.js
  test/index.test.js
Labels: Hacktoberfest

#21 feat: add polish helper method
  src/index.js
  test/index.test.js
Labels: Hacktoberfest

#45 Feat: Added helper for Indian English
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#50 feat: add european portuguese helper method
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#56 Add a helper method for Canadian French
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#65 feat: add helper method for Swedish
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#47 feat: add a helper for french language
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#60 feat: add helper for Spanish US language
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#58 feat(component): implemented helper method for MEXICAN SPANISH
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#63 feat: added Danish helper function
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#62 feat: add castilian spanish helper method
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#28 feat: Adds Norwegian Helper
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#66 feat: add a helper method for Arabic Language
  README.md
  src/index.js
  test/index.test.js
Labels: approved

#57 feat: add a helper method for Welsh Language
  README.md
  src/index.js
  test/index.test.js
Labels: approved
